### ISSUE TITLE
Cannot use a sub query alias in an order by statement in NyQL script

### ISSUE THREAD

**Issue by cjayawickrema** [VirtusaPolarisGTO/NyQL#1]
There is no way to order by a column which comes from a sub query in my select statement.
e.g.
TARGET() ...
FETCH(
QUERY({}...).alias("myCol")
)
ORDER_BY(
DESC(myCol)
)

Above example gives me an error saying DESC not supported. I could not even work around with DESC(NUM(1)).

Both should be supported IMO

**Comment by cjayawickrema** [comment]
was this rolled out?

**Comment by isuru89** [comment]
Fixed in v1.1.1 @cjayawickrema

**Comment by cjayawickrema** [comment]
patch worked. Thanks for the quick fix!
