### ISSUE TITLE
Support for providing config file path as ENV variable

### ISSUE THREAD

**Issue by cjayawickrema** [VirtusaPolarisGTO/NyQL#17]
At the moment, NyQL config can be provided via json file or as environment variables. But it would be even better to have a middle-ground approach to provide the **json file path** via an **environment variable**. This way we can well protect the sensitive config such as passwords that could be easily leaked from env variables, even if encrypted.

**Comment by isuru89** [comment]
This is already there in the engine. You can pass below VM argument to set the config file path from an **environment variable.**

`-Dcom.virtusa.gto.nyql.nyConfigFile=<path-to-config-file>`

**Comment by cjayawickrema** [comment]
Great! I will try this. Please improve the documentation to mention this. Probably another page in wiki for configurations(?).
