### ISSUE TITLE
Cannot use $IMPORT_UNSAFE outside queries

### ISSUE THREAD

**Issue by cjayawickrema** [VirtusaPolarisGTO/NyQL#37]
When i try to use $DSL.$IMPORT in groovy layer it works without any problem. However $DSL.$IMPORT_UNSAFE does not - gives below error. Please provide the support for this.

groovy.lang.MissingMethodException: No signature of method: com.virtusa.gto.nyql.DSL.$IMPORT_UNSAFE() is applicable for argument types: (java.lang.String) values:

**Comment by isuru89** [comment]
This function will be renamed to `IMPORT_SAFE` in v2 to correct its meaning.
