### ISSUE TITLE
WITH ROLLUP Support

### ISSUE THREAD

**Issue by cjayawickrema** [VirtusaPolarisGTO/NyQL#4]
I want to write the NyQL equivalent for following MySQL query that contains WITH ROLLUP. Is there anyway I can achieve this? Could not find this in NyQL wiki.

SELECT year, SUM(profit) AS profit
   FROM sales
   GROUP BY year ASC WITH ROLLUP;

**Comment by cjayawickrema** [comment]
At the moment i am working around this with a native injection as follows.

GROUP_BY("year ASC WITH ROLLUP")

**Comment by isuru89** [comment]
The proposed syntax is; appending _ROLLUP()_ function immediately after GROUP BY function.

```sql
GROUP_BY (columns...) ROLLUP()
```

The function syntax `()` will be used to provide possible subset defining option in the future.
